### ISSUE TITLE
Display runtime version on Validators page

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/testnet-manager#18]
This can be handy when switching between different testnet-managers to compare networks properties.

**Comment by BulatSaif** [comment]
As reference we can use a collator page, it has runtime version: 
![Screenshot from 2023-01-26 16-23-05](https://user-images.githubusercontent.com/24387396/214846375-e0253c9e-c7a9-45e4-9cc0-80bd3b35f154.png)

**Comment by PierreBesson** [comment]
Closing as not really needed anymore as we have a runtime page with full information.
