### ISSUE TITLE
Add runtime upgrades options to better simulate mainnet

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/testnet-manager#49]
It has been pointed out to us by that testnet runtime upgrades should be run in this way to better simulate mainnet upgrades:

1. Wrap `system.setCode` with `utility.with_weight`
2. Wrap the upgrade in `scheduler.schedule_named` to execute it to a delay

I think (1) can be set as new default behavior as an improvement over unchecked weight but (2) can be added as an option with configurable scheduler delay in blocks.

#### Example call:
---
Outer call: scheduler.schedule_named:

    id: can just hash some value and paste in the 32 bytes. E.g. "westend runtime 9360" => 0x50e05872431a08cca63cbce71a6aaf282519baec14f9b852f300d63c7f6ae5fa
    when: some block number in the future
    maybe_periodic: None
    priority: 63
    call: utility.with_weight

utility.with_weight args:

    call: system.set_code and add the runtime compact compressed wasm file
    weight
        ref_time: 1_000_000_000_000 (= 1 sec)
        proof_size: 3_145_728 (= 3 * 1024 * 1024)

**Comment by BulatSaif** [comment]
is it only for relay chain or we should use scheduler also for parachains?

**Comment by PierreBesson** [comment]
Yes scheduler could also be used for parachains but let's do it first for relaychains.

**Comment by PierreBesson** [comment]
Done in #56
