### ISSUE TITLE
Support deploying undying collators into testnet

### ISSUE THREAD

**Issue by bredamatt** [paritytech/testnet-manager#59]
It would be great if the testnet-manager can provide a few routes such as: 
- `api/load-test/deploy-undying`, and
- `api/load-test/delete-undying` 

for scaling load in Versi.

Because the `undying-collator` supports the parameters:
- PoV size
- PVF complexity

it would be very useful if these parameters are also provided. 

A suggestion could be to simply send a POST request with a pre-defined `Pod` spec from the testnet-manager to the kubernetes API, where the PoV size and PVF complexity CLI arguments (to the undying-collator) are parameters.

**Comment by pepoviola** [comment]
We need to also be able to pass the `para_id` since the undying collators needs this as cli flag.

**Comment by bredamatt** [comment]
@PierreBesson Any updates on this?

**Comment by PierreBesson** [comment]
Deploying nodes is outside the scope of the testnet-manager which is designed around read-only access to Kubernetes. Moreover we are currently using the testnet-manager for managing our stable testnets for which such a feature is not desirable. To provide on-demand deploy of custom parachains for load-tests we will have to separate different tool that can then be composed with the testnet-manager API to register parachains programmatically.

**Comment by pepoviola** [comment]
> Deploying nodes is outside the scope of the testnet-manager which is designed around read-only access to Kubernetes. Moreover we are currently using the testnet-manager for managing our stable testnets for which such a feature is not desirable. To provide on-demand deploy of custom parachains for load-tests we will have to separate different tool that can then be composed with the testnet-manager API to register parachains programmatically.

Sounds a nice approach, let me know if I can help you with this new tool.
Thanks!

**Comment by bredamatt** [comment]
Hmm this is strange. I thought it we had established that the tool has already been started: https://github.com/paritytech/touchstone
