### ISSUE TITLE
Add API route for funding and creating new accounts

### ISSUE THREAD

**Issue by bredamatt** [paritytech/testnet-manager#67]
Wrt. load-testing both parachains and relay-chains in Versi, the capability of creating new accounts and funding these is of importance.  This should work for both `tick` and `validators`. 

We could then use a transaction generator binary afterwards that targets specific accounts afterwards for the benchmarks.

**Comment by bredamatt** [comment]
Any updates on this? This is a requirement for load-testing using `sTPS`.

**Comment by PierreBesson** [comment]
Implemented in https://github.com/paritytech/testnet-manager/pull/70
